name: 05 - Event Filters
on:
  push:
    branch:
      - features

jobs:
  echo: 
    runs-on: ubuntu-latest
    steps:
      - name: mostrar_mensaje
        run: echo "Running whenever branch is features"


